rest-nvim/rest.nvim

- lua/rest-nvim/init.lua
This PR disables the interpretation of backslash escapes in the response body rendering command. Should close #10
@rudotriton could you please test it to see if everything is alright?
> fix: disable interpretation of backslash escapes in response body

- lua/rest-nvim/init.lua
This PR should fix the escaping of the single quotes in the response body. Should close #12
@rudotriton could you please test it to see if everything is alright? I didn't tested it, but should be working well.
> fix: escape single quotes in response body

- lua/rest-nvim/init.lua
- tests/using_env_vars/post_create_user.http
By splitting the response body to a table we should be able to use `nvim_buf_set_lines` in one call without having to iterate over all lines, which can take much longer. Also avoids some code duplication
Just gotta figure out how to run the tests, @NTBBloodbath to the rescue plz
> refactor: use lua table for response body

- doc/rest-nvim.txt
- lua/rest-nvim/init.lua
- plugin/rest-nvim.vim
This PR aims to add verbosity to `rest.nvim` by using of the `dry_run` field in the plenary cURL wrapper in the `run` function.
- `<Plug>RestNvimPreview`
- Same as `RestNvim` command but it returns the cURL command without executing the request. Intended for debugging purposes.
---
I have also added more traceback information for when the request fails so it can be debugged faster.
> feat: add verbose command to preview cURL requests

- doc/rest-nvim.txt
- lua/rest-nvim/init.lua
- plugin/rest-nvim.vim
This PR aims to fix the comments that should be ignored but they are being parsed actually. They are being ignored in
- headers (including the auth ones)
- JSON body
Known issues:
- JSON syntax highlight doesn't recognize `#` char so it'll not have the proper highlighting in the request body if there are commented fields.
> fix: ignore commented lines as it should be

- lua/rest-nvim/init.lua
This PR fixes the `get_auth` function returning value so the `Authorization` header value will be successfully passed.
@mr-majkel can you please give it a try? I think that issue was by my side. Already passed an Authorization statement like `Authorization: Bearer random_characters` but I don't have how to properly test it right now, although I think it should work as intended.
Lemme know if the issue is fixed here and if that's the case then let's close the plenary issue regarding to Bearer tokens.
Regards
> refact: handle Authorization as a header

- lua/rest-nvim/init.lua
- tests/using_env_vars/.env
- tests/using_env_vars/post_create_user.http
This PR aims to add the ability to use environment variables for headers values and also cleaned some bad coding styles under the hood. Closes #25 
Test for this feature can be found at [tests/using_env_vars](https://github.com/NTBBloodbath/rest.nvim/tree/feature/header-values-from-env/tests/using_env_vars) directory.
> feat: be able to use environment variables in headers

- lua/rest-nvim/init.lua
- tests/post_create_user_externalfile.http
- tests/user.json
See #31 
import file directive with `< filename.xyz` will call curl with `-d @filename.xyz`
This works with absolute filenames and for relative filenames (where relative filenames will be interpreted as relative to the .http-file)
> allow import files for .http files

- lua/rest-nvim/init.lua
- tests/post_create_user.http
Hi @NTBBloodbath I have faced an issue with the rest-nvim handling of json arrays, e.g. ["a", "b"]. Basically, `vim.fn.json_decode()` that is used by `get_body()` decodes arrays as lua tables with curly braces. After passing them to plenary.curl as body, those are not properly encoded back to square brackets - curly braces are passed to curl, and if the API expects an array the request will fail on the server side.
My suggestion is to benefit from recent development in plenary and pass json always as raw string, and let plenary.curl handle it.
As a side thing, after going through the nvim lua api docs, I have found a function that can be used to find the matching curly brace for delineating the body in the http file. This way the parsing method will not be confused by ill-formatted, …
> make plenary.curl handle json parsing

- lua/rest-nvim/init.lua
Hi @NTBBloodbath, currently httpResult buffer gets modified flag set to true (there is a plus sign on the statusline) if it is reused for another query. This can lead some users (like me;)) to be asked to save or discard the buffer contents. By changing the buftype option of the httpResult to nofile, makes modified flag to be ignored.
Btw. would you consider changing the stylua indentention to spaces? I think it is more common pattern both across lua neovim plugins, and more professional lua projects,  see [luarocks](https://github.com/luarocks/lua-style-guide) for example.
> prevent modified flag switch for httpResult

- lua/rest-nvim/init.lua
Before errors looked like
> E5108: Error executing lua [string ":lua"]:1: [rest.nvim] Failed to perform the request.                                                                                                                      
Make sure that you have entered the proper URL and the server is running.                                                                                                                                     
>                                                                                                                                                                                                              
>Traceback: .../site/pack/packer/start/rest.nvim/lua/rest-nvim/init.lua:214: [rest.nvim] curl error 7: Failed to connect to host.     
Using …
> use nvim_err_writeln for top level error report

- README.md
- doc/rest-nvim.txt
- lua/rest-nvim/config.lua
- lua/rest-nvim/init.lua
This PR aims to allow skipping SSL verification as the title says, this could be useful when dealing with unknown certificates.
To achieve this goal, the changes provides a new `setup()` function option called `skip_ssl_verification` which is `false` by default. If the option `skip_ssl_verification` is `true` then `rest.nvim` will pass the `-k` flag to cURL.
@rafi can you please test it out? :slightly_smiling_face:
> feat: allow skipping SSL verification, closes #46

- README.md
- doc/rest-nvim.txt
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
- lua/rest-nvim/utils/init.lua
- tests/external_file/multiple_requests.http
New feature "highlight request on run() and last()". In order to implement this, we had to switch from synchronous call to plenary-curl to asynchronous with callback. Implementation is similar to the build-in `vim.highlight.on_yank`. This feature is enabled by default.
Additionally, the old feature of moving the cursor to the current request line is disabled by default as the highlighting shows more accurate what is send and in my opinion it is nicer to have the cursor stay in place.
@NTBBloodbath : Any objections?
> Highlight request on run() and last()

- lua/rest-nvim/utils/init.lua
Hi @NTBBloodbath,
This pr adds the loading of .env files in the directory of the currently opened file.
I have a big monorepo structured like
```
├─ backend
│  └─ requests
│        └─  test.http
└─ frontend
```
Currently, I have to place my .env file for common properties in all my .http files in the root folder of my project.
I would like to place them in the same folder where all my requests are.
**Which variables overwrite which?**
Probably .env files in deeper nested directories should overwrite those in upper directories.
**Should .env files in intermediate directories also be loaded?**
Should it also load .env files in `/backend/.env`? Probably it should if that doesn't add a lot of overhead.
Thank you a lot for this awesome plugin @NTBBloodbath,
Cheers, Jim
Edit: 
Sorry for all the …
> Load .env files in dir of currently opened file

- README.md
- doc/rest-nvim.txt
- doc/tags
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/utils/init.lua
Added configuration option for specifying name of the file which consists environment variables.
> feat: config option for custom environment variables file

- README.md
- doc/rest-nvim.txt
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/utils/init.lua
Added configuration option to extend or replace built-in dynamic variables.
Example usage:
```lua
require("rest-nvim").setup({
custom_dynamic_variables = {
-- overwrite built-in
['$uuid'] = function()
return "{{$uuid}}"
end,
-- add new dynamic variable function
["$date"] = function()
local os_date = os.date('%Y-%m-%d')
return os_date
end,
},
})
```
> feat: add config option for custom dynamic variables

- lua/rest-nvim/utils/init.lua
Found this plugin and it's awesome thanks! I was missing fast switching of variables in the document, so I made this feature.
I suppose this will fix #68.
Just an example:
```
host: "service.com"
token:  "PRODUCTION_TOKEN"
username: "manager"
query: 'where={"query":"test"}'
###
GET https://{{host}}/api/users?{{query}}
Authorization: Bearer {{token}}
POST https://{{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}
{
"name": "{{username}}"
}
```
You may fast change/comment/uncomment the variables you need and keep it with your `http` document.
> Document variables

- lua/rest-nvim/request/init.lua
- lua/rest-nvim/utils/init.lua
The VSCode REST client uses a {{$dotenv URL}} pattern to match .env file variables. I work in a team where not everyone uses neovim, so having a cross compatiblity layer for this would be good.
The PR changes how the url is parsed, allowing for spaces in the path and then removing the dotenv references, so that the same markdown works with this client
Example case:
```
GET {{$dotenv URL}}/test/auth
```
> Allow spaces in variable names, and  cross compatibility with $dotenv

- README.md
- doc/rest-nvim.txt
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
Added a new option for the placement of the request buffer:
Current behavior:
```
__________________           _________________________________________________
|GET {{url}}      |         | {{response}}           |  GET {{url}}           |
|                 |   ->    |                        |                        |
|                 |         |                        |                        |
￣￣￣￣￣￣￣￣￣￣￣          ￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
```
New behavior with 'result_split_in_place = true'
```
__________________           _________________________________________________
|GET {{url}}      |         | GET {{url}}            | {{response}}           |
|                 |   ->    |                        |                        |
|                 |         | …
```
> Config request buffer placement

- lua/rest-nvim/curl/init.lua
Currently, the getter for config `result_split_horizontal` is not working because it access the `config` table directly.
I fixed the issue by using `config.get("result_split_horizontal")`.
confirmed working **on my machine** 😃 
I have idea to add config to either show the split in the right (if vertical) or below (if horizontal). should I open issue for that?
the option is to add more config key `reverse_split`, or make a breaking change by deleting existing `result_split_horizontal` then adding:
```lua
setup {
-- ....
split_position = "left", -- possible value: "top" | "right" | "bottom" | "left"
}
```
> fix: result_split_horizontal config getter

- lua/rest-nvim/request/init.lua
When plenary.curl is supplied a raw string as body and if this string contains a `$` it checks for a file path and errs. This seems to be a known issue and a [fix](https://github.com/nvim-lua/plenary.nvim/pull/360) is suggested. This seems to be the root cause.
However, I noticed the `plenary.curl` can also take a[ lua table as `body`](https://github.com/nvim-lua/plenary.nvim/blob/9069d14a120cadb4f6825f76821533f2babcab92/lua/plenary/curl.lua#L182-L193). This PR sends a table as the `body` while invoking plenary.curl, whenever possible. This way we can side-step the upstream issue and also exploit the allowed "overloading".
> [FIX] NTBBloodbath/rest.nvim/issues/102: some payloads can confuse rest.nvim

- rest.nvim-scm-1.rockspec
so that one can install the plugin from luarocks.org .
It helps deal automatically with plugin dependencies.
See https://teto.github.io/posts/2022-06-22-neovim-plugin-luarocks-2.html for more context.
> feat: adding rockspec

- rest.nvim-scm-1.rockspec
this wont work because I had to remove the plenary package from luarocks but it's only temporary: https://github.com/nvim-lua/plenary.nvim/pull/391
should be fine in a couple days.
> rockspec: add missing dependency plenary

- lua/rest-nvim/utils/init.lua
Since this implementation of the `file_exists` function has the ability to give an answer as to whether or not a file exists, it is not completely accurate since giving the `open` function a directory path as an argument will still return `true` indicating that the file exists even though it is not actually a file.
```lua
M.file_exists = function(file)
file = io.open(file, "rb")
if file then
file:close()
end
return file ~= nil
end
````
so I refactored the function, making use of the built-in function`'vim.fn.filereadable`, to ensure that first we are verifying that we are actually reading a file and not a directory, and in turn showing if this file exists or not.
```lua
M.file_exists = function(file)
if vim.fn.filereadable(file) ~= 1 then return false end
return true
end
```
In this way …
> refactor file_exists function

- README.md
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/request/init.lua
This PR provides the option to skip URL encoding the request. I ran into an issue recently where I wanted to provide the URL already encoded, but it was then getting re-encoded causing issues.
> First time contributor, open to feedback.
> Add option to skip encoding url

- .editorconfig
the .editorconfig file helps user autosetup their IDE, the neovim project has one for instance.
NB: I've pushed the branch to the main repo instead of my fork, my bad
> added .editorconfig to help new contributors

- README.md
Swap tabs to spaces so everything is aligned. 😅
> Fix indentation for new `encode_url` option.

- lua/rest-nvim/request/init.lua
This PR fixes `get_body` for cases when body definition has only one line.
Files like [tests/external_file/post_create_user.http](https://github.com/rest-nvim/rest.nvim/blob/4a23d38726c0b3c5a2de9f927de5b0b518bdf4f7/tests/external_file/post_create_user.http) are not working as expected. 
When we open it and run `:lua require("rest-nvim").run(true)` the current result is
```
[rest.nvim] Request preview:
curl -sSL --compressed -X 'POST' -H 'Content-Type: application/json' 'https://reqres.in/api/users'
```
but the expected is
```
[rest.nvim] Request preview:
curl -sSL --compressed -X 'POST' -H 'Content-Type: application/json' --data-raw '{"name": "morpheus", "job": "leader", "time": "1667482599"}' 'https://reqres.in/api/users'
```
> Fix get_body function

- README.md
- doc/rest-nvim.txt
This commit updates the README and doc/rest-nvim.txt with references to `rest-nvim/rest.nvim` instead of `NTBBloodbath/rest.nvim`
Other occurences of NTBBloodbath in the license were ignored for now as I'm not sure if that should be included in this PR.
> Update github references to rest-nvim/rest.nvim

- lua/rest-nvim/config/init.lua
- lua/rest-nvim/request/init.lua
- tests/post_json_form.http
Fixes errors when you pass array or object in request body without setting request body to `application/json`, for example:
```http
POST http://localhost:8000/login
{
"username": "foo",
"args": {
"key": "val"
}
}
```
would result in following error:
```
[rest.nvim] Failed to perform the request.
Make sure that you have entered the proper URL and the server is running.
Traceback: ...site/pack/packer/start/plenary.nvim/lua/plenary/curl.lua:54: attempt to concatenate a table value
```
but this PR fixes it and gives the following query:
```bash
curl -sSL --compressed -X 'POST' -d 'args={"key": "val"}' -d 'username=foo' 'http://localhost:8000/login'
```
> fix parsing of nested tables and curl arguments

- lua/rest-nvim/request/init.lua
Instead of converting the captured header name to lowercase using it the way it is spelled in the document.
> #141: fixes header name

- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
- lua/rest-nvim/utils/init.lua
- tests/main_spec.lua
We want to be able to run a whole .http file . 
The dance around cursor position is quite annoying.
> test: programmatic run of .http file

- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
- fix(log): dont hardcode log level
- fix: error when run_request is run without { verbose = XXX }
> fix debug msg

- README.md
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/request/init.lua
Fixes error caused by html formatter running even when tidy is not available on the system. Also fixes docs related to disabling formatters.
> This PR is a cleaner version of #165.
---
**Reason why formatter should be set to `false` instead of `nil`:**
`nil` means nothing, ie. absence of value; that's why you have how pass `false` instead which has a actual value `0` in binary which can be set to a variable and passed around.
Here's another analogy:
Let's say you asked me to put something in a box, and I put `<nothing>` in the box. Is the box now empty or does it contain `nothing`? There is no way for you to verify that.
Fixes #157  hardcoded lower casing of content-type.
> fix: formatter for html and special casing of content-type

- lua/rest-nvim/init.lua
Allow users to call `.run()` without passing `true|false` for verbose parameter.
relates #166
> Add default `opts` for .run_request function

- doc/rest-nvim.txt
- doc/tags
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
- lua/rest-nvim/utils/init.lua
- plugin/rest-nvim.vim
- tests/post_create_user.http
- tests/script_vars/.env
- tests/script_vars/script_vars.http
- tests/swappable_env/.env
- tests/swappable_env/.env.json
- tests/swappable_env/swappable_env.http
This addresses [#110](https://github.com/NTBBloodbath/rest.nvim/issues/110) as well as allowing the env files to be updated using a lua script inside {% script %} tags, similar to the intellij rest client. The lua code in the script tag will is passed a context table which includes the response, json_decode and a function to write/set environment variables. This is mostly useful for myself when I am working with authenticated apis.
example: 
```
POST https://jsonplaceholder.typicode.com/posts
{
title: 'foo',
body: 'bar',
userId: 1,
}
{% 
local body = context.json_decode(context.result.body)
context.set_env("postId", body.id)
%}
PATCH https://jsonplaceholder.typicode.com/posts/{{postId}}
{
title: 'foo',
}
```
Environment files can also easily be swapped using the :RestSelectEnv command …
> feat: Add option for json env and allow manipulating env files during the session

- .github/workflows/release.yml
publish rest.nvim automatically on luarocks upon new tag https://github.com/mrcjkb/luarocks-tag-release
one would need to add a LUAROCKS_API_KEY to the repo secrets, I dont have the rights but @NTBBloodbath can. I can give you such a key via mail if you want.
> ci: add tag release workflow

- lua/rest-nvim/utils/init.lua
fixes https://github.com/rest-nvim/rest.nvim/issues/89
I see there's https://github.com/rest-nvim/rest.nvim/pull/115, but this is a one-character change, would you like to consider it? Thanks anyways
> Exclude encoding `@` to support `user:pass@host` authentication

- rest.nvim-scm-1.rockspec
- rest.nvim-scm-3.rockspec
Fixes the missing documentation was missing when installing through luarocks.
Also, I noticed the following error when checking the `luarocks` build:
```
Error: Inconsistency between rockspec filename (rest.nvim-scm-1.rockspec) and its contents (rest.nvim-0.1-2.rockspec).
```
I changed both to `scm-3` but maybe another major is better.
> fix: include documentation on rockspec

- .github/workflows/default.yml
- flake.nix
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/request/init.lua
- lua/rest-nvim/utils/init.lua
I was testing an API that returned a zip file and it was getting out of
hand so I added an is_binary_content_type to control whether to display
the content type.
Ideally I would have liked the display to be a default postprocess step so
that it gets more generic and let the user more control but this needs
deeper refactoring.
> dont display binary outputs in answer

- README.md
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
This is gated behind a flag at false by default because it can be quite verbose.
Sometimes we may want to rerun the command run by rest.nvim with additional parameters, for instance to save the output in a specific file.
> feat: add config.show_curl_command

- doc/rest-nvim.txt
- lua/rest-nvim/init.lua
This is a quick & dirty implementation of https://github.com/rest-nvim/rest.nvim/pull/214, e.g., rest-nvim throws events when 
- launching a request
- finishing a request
This is what I intented to test it with
```
local start_time = 0
local on_start_request =  function (req)
-- vim.loop.gettimeofday()
-- vim.fn.reltime()
start_time = vim.loop.now()
print("starting request")
end
local on_stop_request =  function  (...)
print("finished request")
-- TODO displayu time taken
end
vim.api.nvim_create_autocmd("User", {
pattern = "RestStartRequest",
once = true,
callback = function()
print("IT STARTED")
end,
})
```
> add callbacks on start/stop request

- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
the treesitter backend is promising but it is too much work to reach feature parity with our current parser: 
https://github.com/rest-nvim/rest.nvim/pull/174
what I am proposing here is a first refactoring to delay variable splicing until last minute. 
It untangles parsing & running requests. Right now you need variables to exist when parsing which means you have to execute the request when parsing them else you get errors.
This PR replaces (aka "splices") the variables at the last minute so you can parse requests without executing them.
It allowed me to add a `buf_list_request` function in the current backend, which was not possible before, so now `run_file` is backend agnostic (it first lists requests and then run them).
In this PR, you can't change backend yet but in a future one, I …
> separate parsing from running steps

- README.md
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/request/init.lua
- doc: mention debug instructions
- feat: make it possible to not inline external file
if you reference a file via <@ file instead of < file the filename will be passed as is to curl, thus making the curl command in preview a ton shorter.
> dont inline file

- lua/rest-nvim/init.lua
run_request and run_file request opts did not use the highlight.enabled setting from config, the default requestOpts prevented the current request to be hignlighted. Added the missing config to the creation of final request ops
> Fix request hightlight

- doc/tags
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
Hello :)
Events implementation as proposed in [214](https://github.com/rest-nvim/rest.nvim/pull/214) seems to work incorrectly. 
Issue 1:
Because a `callback` function is passed to plenary's curl, the request will be made asynchronously, causing the `RestStopRequest` event to be emitted right after the `local success_req, req_err = pcall(curl.curl_cmd, Opts)` returns, way before the actual request finishes. 
Issue 2:
The events are emitted only during normal `run_request`, they are not emitted during rerunning the `last` request. 
Proposed changes: 
1. Move the emition of events into the `curl/init.lua` file. This way it won't matter if the call is made via `run_request` or `last` method.  I'm actually not sure about his one though. Maybe it would be better to extract the events back to …
> Fix RestStopRequest event 

- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/utils/init.lua
It would be great if rest.nvim would support setting variables on running post request scripts without storing these values on hard disk, or without modifying existing .env files. This PR proposes a change for the post-script context and variable resolution to store values in an in-memory table and be able to resolve templates from these values as well. 
This in-memory context is bound to the currently used environment, so switching between them also switches between the in-memory stores as well.
Example situation where the IN_MEMORY_FIELD is available for resolution, but the runner not altering the .env file: 
```http
GET http://url/endpoint
{%
local body = context.json_decode(context.result.body)
context.set("IN_MEMORY_FIELD", body.field)
%}
GET http://url/endpoint/{{IN_MEMORY_FIELD}} …
```
> [Feature] In-memory environment for post request scripts

- README.md
I added the lazy.nvim setup in README file, nothing more.
> docs: add lazy.nvim setup in README

- lua/rest-nvim/request/init.lua
Fixes #173.
This isn't a treesitter solution, but it's at least a quick and easy, if only temporary, patch.
1. start_request was searching forward from the cursor position. Adding 'b' to the search flags fixed that.
2. Both start_request and end_request depended on the user having set 'nowrapscan' to prevent wrapping around the end of the file. Such wrapping could result in finding the wrong query. Adding 'W' to the search flags fixed that, and removed the need for the stopline parameter.
3. Refactored the way last_line is used in end_request.
> Fix finding the start and end of the current query.

- lua/rest-nvim/curl/init.lua
Some related issues:
- #246
- #248
`res.headers` is not a `key:value` table, so it can't extract the content-type properly, as below:
```lua
{
"Content-Type: application/json; charset=utf-8",
"Date: Thu, 16 Nov 2023 15:54:51 GMT",
"Content-Length: 614"
}
```
convert `res.headers` to `key:value` table.
And, I changed `headers` structures in context: `context.result.headers`. 
Before, it was the above structure, now:
```lua
{
["Content-Type"]: "application/json; charset=utf-8",
["Content-Length"]: "614",
"Date": "Thu, 16 Nov 2023 15:54:51 GMT"
}
```
--- 
This plugin is awesome, really straightforward and user-friendly. Thanks a lot for your hard work!
> Fix: content-type cannot be extracted from headers

- README.md
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
- lua/rest-nvim/init.lua
- lua/rest-nvim/utils/init.lua
This PR adds the option to configure statistics for requests with the curl `--write-out` option.
Statistics are added after the headers but before the body, and are by default disabled so this is an opt in feature and won't affect any existing configurations.
There are a couple of ways to configure statistics, either with a string or with a statistics spec. I didn't know how to properly convey this in the README.md, so any suggestions are welcome.
The two different config options are shown below and can be mixed together also.
```lua
{
result = {
show_statistics = { "time_total", "size_download" }
}
}
```
```lua
{
result = {
show_statistics = {
{ "time_total", title = "Total time: ", type = "time" },
{ "size_download", type = "byte" },
}
}
```
They will output respectively (queries ran on …
> feat: add request statistics

- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
When you run request for this first time, focus is getting switched to the new windows with results buffer.
I've added simple flag that allows to configure this behavior: either stay in current windows (.http file) or change to results window (default)
> feat: stay in current window on split

- lua/rest-nvim/init.lua
fix for non json body like form data:
```http
POST https://httpbin.org/post
Content-Type: application/x-www-form-urlencoded
a=1&b=2
```
> fix: return non json body

- lua/rest-nvim/request/init.lua
in the original code, the `host` header will add to the url. maybe it allows the url part only have the path part. but if it’s a complete url, it will form a invalid url.
so the change is : add host before url only if it starts with '/', otherwise it probably starts with 'http'.
> fix bug when headers have  `host`

- lua/telescope/_extensions/rest.lua
When trying to select an environment file with the Telescope extension, the underlying `fd -H` command would match hidden files, but not files that are matched by `.gitignore`. Adding the `-I` option matches files that are ignored by git.
Fixes #283
> Telescope extension can select env files ignored by git

- doc/rest-nvim.txt
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/curl/init.lua
- lua/telescope/_extensions/rest.lua
Adds a new configuration option that allows to set a lua script that is executed before each request. This script receives the request opts (body, headers, url, etc.) and the environment variables.
This allows to dynamically modify the opts (body, headers, url, etc.) before executing the request. For example compute some signature based on the request body and some key to set the Authorization header etc.
> Add pre-script configuration.

- README.md
Without this, the filetype is not applied correctly.
#184
> docs: add `ft` to `lazy.nvim` config example

- README.md
Added a bit to documentation about getting telescope extension to work on Ubuntu and Debian systems
> Telescope extension Doc dev

- lua/rest-nvim/curl/init.lua
I have found a bug using the contentful api. This api returns this content type: 
```
Content-Type: application/vnd.contentful.delivery.v1+json
```
Currently the content type is `vnd` instead of `json`. 
I have added this fix, but I think can be improved  extending to all the content types this plugin want to support, probably are only 3: json, html and txt. let me know what you think, and thanks for this great plugin 🎉
> Get json content type for custom content types

- lua/rest-nvim/result/help.lua
Copied from the body of the commit:
> Problem:
> 
> The help window causes an error when calling `vim.api.nvim_open_win` because the width being passed is not an integer.
> 
> Neovim's `vim.api.nvim_open_win` function requires that the width and height be specified in whole integers.
> 
> The width is being calculated through a division operation causing it to potentially be a number that is not an int.
> 
> Solution:
> 
> Floor the calculation of the help window width so the width is always rounded down to the nearest integer and can thus be used with `vim.api.nvim_open_win`.
> fix: ensure help window width is an int

- lua/rest-nvim/parser/init.lua
Copied from the body of the commit:
> Problem:
> 
> Placing cursor between a request method and a uri and then invoking `:Rest run` causes the node to be incorrectly parsed leading to an error.
> 
> See the following where the column above the caret (^) denotes the cursor position:
> 
> ```
> GET https://google.com
>    ^ cursor above caret
> ```
> 
> Running this will cause an error. This is because the `parser.parse_request` method cannot handle Treesitter nodes of type `request`.
> 
> Solution:
> 
> Make the `parser.parse_request` function handle Treesitter nodes of type `request` by recursively calling itself on the `request` node and taking that output when it finds a `request` node.
Example of the problem with a recording:
This problem implies a deeper issue to my eyes as I noticed …
> fix(parser): make `parse_request` handle `request` TS nodes

- .editorconfig
Neovim supports `editorconfig` now, it has a builtin plugin for it. See `:h editorconfig`.
This change ensures editors pick up the correct `indent_size` (like Neovim) and set their indent sizing correctly.
`stylua.toml` is using the indent size as 2, so I set all lua files to use an indent size of 2 as well in the editorconfig.
It was driving me a tiny bit bonkers having to run `:set shifwidth=2` on every lua file while working on something else 😄.
> chore: set `lua` indent_size in editorconfig

- README.md
This PR updates the rest.nvim README with the newest changes related to luarocks.nvim. Once this gets merged I'll also merge the luarocks.nvim `go-away-python` branch into `main`.
The `go-away-python` branch removes the need for python as an external dependency, completely eliminates hererocks, fixes several bugs on different platforms and generally tries to provide a more streamlined experience. That does come unfortunately at the cost of a breaking change, but such is life sometimes :)
This will probably be the last breaking change luarocks.nvim has in a *while*.
> docs(README): update instructions to adapt to latest `luarocks.nvim` changes

- lua/rest-nvim/result/winbar.lua
This should avoid errors as reported on issue #339
> fix(functions): handle highlights of winbar result with prefixed zeros

- lua/rest-nvim/result/winbar.lua
Cleaner way for padding with zeroes.
Related to: #339
> ref(winbar): pad the hex with 6 zeroes using string.format

- README.md
- lua/rest-nvim/autocmds.lua
- lua/rest-nvim/config/check.lua
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/result/help.lua
There was added new table in `result` table named `keybinds`. With this table you can redefine mapping for `cycle_result_pane` action. To do this, in config you need to add
```lua
result = {
keybinds = {
prev = "J", -- or any
next = "K", -- or any
}
}
```
Other feature is ability to choose does these mappings attach to request result buffer or not. If you want to make mappings locally in buffer, add
```lua
result = {
keybinds = {
-- ...
buffer_local = true
}
}
```
This feature is useful if you already have other actions mapped with `H` or `L`.
Defaults for `result.keybinds` are following:
```lua
keybinds = {
buffer_local = false,
prev = "H",
next = "L",
}
```
So plugin acts like before if `keybinds` is not set.
> feat: custom mappings for cycle result pane

- lua/rest-nvim/client/curl.lua
Fixes #317 
Splits the query into individual parameters and appends each one to the url using the `U_APPENDQUERY` flag. Handling of the `=` character is not needed due to how the flag works:
> When [CURLU_APPENDQUERY](https://curl.se/libcurl/c/curl_url_set.html#CURLUAPPENDQUERY) is used together with [CURLU_URLENCODE](https://curl.se/libcurl/c/curl_url_set.html#CURLUURLENCODE), the first '=' symbol is not URL encoded.
See https://curl.se/libcurl/c/curl_url_set.html#CURLUAPPENDQUERY
> fix: correctly urlencode query parameters

- README.md
- lua/rest-nvim/config/init.lua
Instead of global keymaps only HL for switching tabs when focused on that buffer as the default behavior.
> fix: change default HL behavior

- README.md
The `keybinds` field used for navigating the tabs for the results was under `results.behavior.keybinds` instead of `results.keybinds`. I checked the code [here](https://github.com/rest-nvim/rest.nvim/blob/main/lua/rest-nvim/config/check.lua#L61-L65) to figure out the correct setup, as `results.behavior.keybinds` was producing the following error:
```
[rest.nvim] WARN: Unrecognized configs found in setup: { "result.behavior.keybinds" }
```
> docs(README.md): fix the config to match what the code expects

- lua/rest-nvim/result/init.lua
HTTP headers are case insensitive. However, rest.nvim failed parsing lowercase `content-type` header
> fix: match lowercase content-type header

- README.md
Fixed README instructions to include missing dependencies for automatic LuaRocks installation
> docs: add missing dependencies for lazy config

- lua/rest-nvim/parser/init.lua
This PR removes the luanil opts from the `vim.json.decode`, since when they are provided all instances of key-value pairs with null values are removed, see my issue in [neovim](https://github.com/neovim/neovim/issues/28619). lua-tables cannot hold nil values:
```
Like indices, the value of a table field can be of any type (except `nil`). In
particular, because functions are first-class values, table fields may contain
functions. Thus tables may also carry methods (see |lua-function-define|).
```
which is the root cause to this behavior.
> refactor: remove luanil opts for vim.json.decode

- README.md
I messed up with luarocks release.
Didn't thought we can't depend on `scm` version
> docs: add `:TSInstall` in readme

- lua/rest-nvim/utils.lua
This patch updates the regex pattern for the time_str to support the format `Tue, 18-Feb-2025 09:59:46 GMT`
> fix(parse http time): update lua pattern to support hyphen separated date

- lua/rest-nvim/client/curl/cli.lua
- lua/rest-nvim/config/check.lua
- lua/rest-nvim/config/default.lua
- lua/rest-nvim/config/init.lua
- lua/rest-nvim/ui/result.lua
- rest.nvim-scm-1.rockspec
- syntax/http_stat.vim
Hello, If I add more statistics like 
```lua
vim.g.rest_nvim = {
clients = {
curl = {
statistics = {
remote_ip = { winbar = "ip", title = "Remote IP" },
time_total = { winbar = "time", title = "Time" },
time_namelookup = { title = "Time dns" },
time_connect = { title = "Time connect" },
time_pretransfer = { title = "Time pretransfer" },
time_redirect = { title = "Time redirect" },
time_starttransfer = { title = "Time starttransfer" },
size_download = { title = "Download size", winbar = false },
speed_download = { title = "Download speed", },
size_upload = { title = "Upload size" },
speed_upload = { title = "Upload speed" },
},
},
},
}
```
In first I got 
```
Warning  WARN [rest.nvim] Unrecognized configs found in setup: { "clients.curl.statistics.speed_download", …
```
> fix(statistics): allow all curl statistics, ordering, highlight

- lua/rest-nvim/dotenv.lua
Now if it ends in json it will try to parse it as json, else it will fallback to .env file parsing. 
Fixes issue #459
> fix: remove env file extension validation

- lua/rest-nvim/commands.lua
- lua/rest-nvim/ui/result.lua
- plugin/rest-nvim.lua
- queries/rest_nvim_result/folds.scm
- queries/rest_nvim_result/highlights.scm
- queries/rest_nvim_result/injections.scm
fix #424
close #73 
Seems working, but I’ll take some time to ensure that this doesn’t break with other plugins like `nvim-treesitter` or `rocks-treesitter.nvim`
> fix(ui): always use `rest_nvim_result` filetype (2nd attempt)

- lua/rest-nvim/utils.lua
- spec/utils_spec.lua
> fix: handle when format target is empty string (# 473)

- lua/rest-nvim/utils.lua
- spec/utils_spec.lua
> fix(utils): safely call `:normal gggqG` (fix #478)

- lua/rest-nvim/parser/init.lua
- spec/parser/http_parser_spec.lua
> fix: expand variables in content type application/x-www-form-urlencoded

- .github/workflows/luarocks.yml
- Makefile
- rest.nvim-scm-1.rockspec
- **fix: handle localhost domains in cookies**
- **feat: use tree-sitter-http parser from luarocks dependency**
> tree-sitter-http parser as luarocks dependency

- lua/rest-nvim/commands.lua
- lua/rest-nvim/request.lua
Run request before opening window which can lead unwanted cursor move when `'splitkeep'` is not `topline`.
Fixes #464
> fix: run request before UI open

- lua/rest-nvim/init.lua
- lua/rest-nvim/parser/init.lua
- lua/rest-nvim/request.lua
> fix: prevent buffer change while parsing

- lua/rest-nvim/ui/result.lua
The Statistics syntax highlight is broken due to missing "http_stat" treesitter language. Not starting treesitter when the language is missing will fallback to the "http_stat" vim syntax defined in the project.
Before:
After:
> Fix Statistics syntax highlight

- lua/rest-nvim/parser/init.lua
This is essentially the same change as in this commit https://github.com/rest-nvim/rest.nvim/commit/9800b593034770fee5eb460ff0e8f0b13de83300
With this change,  [in place variables](https://www.jetbrains.com/help/idea/exploring-http-syntax.html#in-place-variables) can be defined like this
```http
@token={{$dotenv TOKEN}} 
```
> feat: allow $dotenv tags in variables
