rest-nvim/rest.nvim

lua/rest-nvim/init.lua
lua/rest-nvim/utils/init.lua
tests/post_create_user.http

- fix broken import files (reverted unnecessary use of raw_body from yesterdays PR)
- fix broken header extraction
- better / more reliable support for multiple requests in one file
- jump to the request line of the chosen request
- curl error messages

Improvements

---

README.md
lua/rest-nvim/init.lua

As i split my buffers across vertical splits, it's better for me to have results on horizontal splits.

Settings to open result on a horizontal split

---

lua/rest-nvim/config.lua
lua/rest-nvim/init.lua

This PR aims to improve how `rest.nvim` handles user configurations in the `setup()` function

refact: improve how setup configurations are handled

---

lua/rest-nvim/utils/init.lua

fix: env var interpolation regex expression

---

README.md
lua/rest-nvim/config/init.lua
lua/rest-nvim/curl/init.lua

Sometimes I just need the result and don't care bout other parts. I don't want to scroll to get to the response body.

Allow hiding specific parts of the result like url, headers, and http info.

---

README.md
doc/rest-nvim.txt
lua/rest-nvim/config/init.lua
lua/rest-nvim/curl/init.lua

feat: yank executable curl cmd

---

lua/rest-nvim/init.lua

make RestNvimLast re-run the last run query and not a preview

---

lua/rest-nvim/request/init.lua

fix: missing argument to end_request

---

Makefile

makes the available actions more discoverable.
Ideally we shouldn't have to push and wait for CI to find issues with a
PR.

adds a Makefile

---

lua/rest-nvim/request/init.lua
tests/env_vars/.env
tests/env_vars/post_create_user.http
tests/env_vars/user.json

It is now possible to run:
< {{HOME}}/my_json_file

feat: support variables in path towards the file to load as well

---

lua/rest-nvim/request/init.lua
lua/rest-nvim/utils/init.lua

Added the ability to declare variables by starting them with @, and then using them as environmental variables, Ala [rest-client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client).
I.E:
@address = localhost
@port = 3000
@base = api
@url = http://{{ address }}:{{ port }}/{{ base }}
would result in url = http://localhost:3000/api
// Had to redo everything to fix the history

Variable substitution

---

README.md

- doc: mention some of the competition

document competition

---

contrib/flake.lock
contrib/flake.nix

I am a nix zealot and having a flake.nix helps me develop for the tool, it brings every dependency I need in the scope when running `nix develop ./contrib`. 
Hopefully it can help other users contribute too.
I will maintain the flake

add flake to help with development

---

.github/workflows/default.yml
.luacheckrc
Makefile
README.md
contrib/flake.nix
lua/rest-nvim/curl/init.lua
lua/rest-nvim/init.lua
lua/rest-nvim/request/init.lua
rest.nvim-scm-1.rockspec
tests/main_spec.lua

Run 'make test' to run tests.
Tests could drive the API towards a more programmatic interface.
This is just a bootstrap to future work.

feat: introduce a testing framework

---

README.md

README: mention vim-rest-console

---

ftplugin/http.vim

so that vim-commentary (for instance) can comment parts of the file

add commentstring

---

doc/rest-nvim.txt
plugin/rest-nvim.vim

Fixes https://github.com/rest-nvim/rest.nvim/issues/215

feat: adding a RestLog command

---

README.md
lua/rest-nvim/curl/init.lua

Kinda WIP. Before merging this, I would like to tag a release first so that users can remain on a stable version of the plugin.
Mostly changes related to https://github.com/neovim/neovim/pull/21474

nvim 0.9 fixes

---

lua/rest-nvim/result/init.lua

fix https://github.com/rest-nvim/rest.nvim/issues/294

fix: ignore error log and adding syntax highlights for result when can not get the res_type

---

README.md

Added a bit to documentation about getting telescope extension to work on Ubuntu and Debian systems

Telescope extension Doc

---

lua/rest-nvim/client/curl.lua

fix(run last): not modify body in order to use it again

---

README.md

This lets non-telescope users select the environment with better ux

docs: add alternative for selecting environment

---

README.md
doc/rest-nvim-api.txt
doc/rest-nvim.txt
flake.lock
flake.nix
lua/rest-nvim/api.lua
lua/rest-nvim/config/default.lua
lua/rest-nvim/config/init.lua
lua/rest-nvim/health.lua
lua/rest-nvim/utils.lua
spec/utils_spec.lua

Add more debug logs and checkhealth logic for `gq` formatting to help users debugging response formatting feature

feat: add more checkhealth for `gq` formatting

---

lua/rest-nvim/commands.lua
lua/rest-nvim/logger.lua
lua/rest-nvim/ui/result.lua
plugin/rest-nvim.lua
queries/rest_nvim_result/folds.scm
queries/rest_nvim_result/highlights.scm
queries/rest_nvim_result/injections.scm

fix(ui): use `rest_nvim_result` filetype for all panes (fix #424)

---

lua/rest-nvim/utils.lua

fix: scope and buf number in setting options

---

lua/rest-nvim/config/init.lua
lua/rest-nvim/parser/init.lua
spec/examples/request_body/graphql.http
spec/parser/http_parser_spec.lua

fix: handle graphql without json variables (close #470)

---

lua/telescope/_extensions/rest.lua

fix(telescope): pass correct file sorter (close #481)

---

flake.lock
flake.nix
nix/plugin-overlay.nix
nix/test-overlay.nix
nix/tree-sitter-http.nix
rest.nvim-scm-1.rockspec
spec/minimal_init.lua

testing with nix to automatically test for both stable & nightly neovim

testing with nix
